source 'https://rubygems.org'
ruby '2.1.2'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-contrib'
gem 'sinatra-asset-pipeline', require: 'sinatra/asset_pipeline'
gem 'sinatra-support'
gem 'rack-flash3'
gem 'sprockets'
gem 'sprockets-helpers'
gem 'unicorn'
gem 'opal'
gem 'opal-jquery'
gem 'opal-activesupport'
gem 'uglifier'
gem 'compass'
gem 'bootstrap-sass'
gem 'activesupport'
gem 'activemodel'
gem 'i18n'
gem 'rubyzip', '>= 1.0.0'

group :development, :test do
  gem 'foreman'
  gem 'rake'
  gem 'rspec'
end
